#include "builder.h"
#include "fs.h"

struct builder builder={0};

/* --help
 */
 
static void print_help() {
  fprintf(stderr,
    "Usage: %s -oOUTPUT INPUT [-tTYPE] [-hHEADER]\n"
    "TYPE: map tilesheet sprctl\n"
    "HEADER is usually 'mid/resid.h', generated by our Makefile and eggdev.\n"
    ,builder.exename
  );
}

/* Guess data type.
 */
 
static const char *guess_type() {
  const char *p=builder.srcpath;
  while (*p) {
    const char *token=p;
    int tokenc=0;
    while (*p&&(*(p++)!='/')) tokenc++;
    if ((tokenc==3)&&!memcmp(token,"map",3)) return "map";
  }
  //TODO We're free to examine (builder.src) too. Seems overkill; our resources should always be in a directory with the type's name.
  return 0;
}

/* Main.
 */
 
int main(int argc,char **argv) {

  if ((argc>=1)&&argv&&argv[0]&&argv[0][0]) builder.exename=argv[0];
  else builder.exename="builder";
  int i=1; for (;i<argc;i++) {
    const char *arg=argv[i];
    if (!arg||!arg[0]) continue;
    if (!strcmp(arg,"--help")) {
      print_help();
      return 0;
    }
    if (arg[0]!='-') {
      if (builder.srcpath) {
        fprintf(stderr,"%s: Multiple inputs.\n",builder.exename);
        return 1;
      }
      builder.srcpath=arg;
    } else if (arg[1]=='o') {
      if (builder.dstpath) {
        fprintf(stderr,"%s: Multiple outputs.\n",builder.exename);
        return 1;
      }
      builder.dstpath=arg+2;
    } else if (arg[1]=='t') {
      if (builder.type) {
        fprintf(stderr,"%s: Multiple types.\n",builder.exename);
        return 1;
      }
      builder.type=arg+2;
    } else if (arg[1]=='h') {
      if (builder.hdrpath) {
        fprintf(stderr,"%s: Multiple resid headers.\n",builder.exename);
        return 1;
      }
      builder.hdrpath=arg+2;
    } else {
      fprintf(stderr,"%s: Unexpected argument '%s'\n",builder.exename,arg);
      return 1;
    }
  }
  if (!builder.dstpath||!builder.srcpath) {
    print_help();
    return 1;
  }
  
  /**
  fprintf(stderr,
    "%s:%d:TODO: Generate '%s' from '%s' of type '%s' with header '%s'\n",
    __FILE__,__LINE__,builder.dstpath,builder.srcpath,builder.type,builder.hdrpath
  );
  /**/
  
  if ((builder.srcc=file_read(&builder.src,builder.srcpath))<0) {
    fprintf(stderr,"%s: Failed to read file.\n",builder.srcpath);
    return 1;
  }
  
  if (!builder.type&&!(builder.type=guess_type())) {
    fprintf(stderr,"%s: Unable to guess data type. Please specify with '-tTYPE'.\n",builder.srcpath);
    return 1;
  }
  
  int err=-1;
  if (!strcmp(builder.type,"map")) {
    err=builder_compile_map();
  } else if (!strcmp(builder.type,"tilesheet")) {
    err=builder_compile_tilesheet();
  } else if (!strcmp(builder.type,"sprctl")) {
    err=builder_compile_sprctl();
  } else {
    fprintf(stderr,"%s: Unknown data type '%s' for file '%s'\n",builder.exename,builder.type,builder.srcpath);
    err=-2;
  }
  if (err<0) {
    if (err!=-2) fprintf(stderr,"%s: Unspecified compiler error (type='%s')\n",builder.srcpath,builder.type);
    return 1;
  }
  
  if (file_write(builder.dstpath,builder.dst.v,builder.dst.c)<0) {
    fprintf(stderr,"%s: Failed to write file, %d bytes\n",builder.dstpath,builder.dst.c);
    return 1;
  }
  
  return 0;
}
